import type { Locale } from '../../domain'

export const behaviourCopy = Object.freeze({
  en: {
    metaLibrary: 'Behaviour Explorer | ADHD Interactive Explorer',
    metaDetail: 'Behaviour Explorer',
    kicker: 'Behaviour Explorer',
    libraryTitle: 'Start with an everyday behaviour',
    librarySummary: 'Browse recognizable experiences and explore several factors that could contribute. This is education, not interpretation.',
    searchLabel: 'Search behaviours',
    searchPlaceholder: 'Search everyday language or canonical labels',
    results: 'behaviours shown',
    noResults: 'No behaviours match this search.',
    explore: 'Explore this behaviour',
    orientation: 'See several possible Context and Regulation pathways. No choices are accumulated.',
    back: 'All behaviours',
    canonicalBehaviour: 'Canonical Behaviour',
    pathwayHeading: 'Several possible educational pathways',
    pathwayIntroduction: 'Choose one pathway to examine. Each option has equal visual weight and follows stable source order.',
    possiblePathway: 'Possible pathway',
    selectedPathway: 'Selected educational pathway',
    context: 'Possible Context',
    contextExplanation: 'Context may change demand, stability, expression, or consequences. It does not prove ADHD.',
    regulation: 'Possible Regulation pathway',
    regulationExplanation: 'This Regulation concept may contribute to the behaviour in this pathway. It is not a personal mechanism diagnosis.',
    pattern: 'Possible recurring Pattern',
    patternIntro: 'When this occurs repeatedly, it may contribute to one of these recurring patterns.',
    noPattern: 'No optional recurring Pattern is associated with this Behaviour in the current knowledge release.',
    function: 'Possible areas of impact',
    functionIntro: 'These examples describe possible Functional Domains. They are not severity ratings or individualized impairment assessments.',
    noFunction: 'No optional Functional Domain example is associated with this Behaviour in the current knowledge release.',
    alternatives: 'Other possible contributors',
    alternativesIntro: 'These possibilities follow source order. The explorer does not decide which, if any, applies to a person.',
    evidence: 'View relationship evidence',
    closeEvidence: 'Close evidence preview',
    evidencePreview: 'Contextual evidence preview',
    evidenceLevel: 'Evidence level',
    evidenceLimitations: 'Limitations',
    relationshipLimitation: 'Relationship limitation',
    sourceCount: 'source records',
    sourceLanguage: 'Scientific metadata is shown in its authoritative source language.',
    evidenceUnavailable: 'Relationship-specific evidence is unavailable for this illustrative example.',
    reset: 'Reset this exploration',
    mapLink: 'See this Behaviour in the full system',
    contextLink: 'Explore why this Behaviour may vary across situations',
    invalidTitle: 'Behaviour not found',
    invalidMessage: 'This exact canonical Behaviour ID is not part of the published Behaviour library.',
    invalidPathway: 'That exact pathway does not belong to this Behaviour. The default exploration state is shown.',
    returnLibrary: 'Return to the Behaviour library',
    semantics: { MODULATES: 'modulates', CONTRIBUTES_TO: 'contributes to', FEEDBACK_WITH: 'has feedback with' },
  },
  fa: {
    metaLibrary: 'کاوشگر رفتار | کاوشگر تعاملی ADHD',
    metaDetail: 'کاوشگر رفتار',
    kicker: 'کاوشگر رفتار',
    libraryTitle: 'با یک رفتار روزمره آغاز کنید',
    librarySummary: 'تجربه‌های آشنا را مرور کنید و چند عامل احتمالی مؤثر را ببینید. این تجربه آموزشی است، نه تفسیر فردی.',
    searchLabel: 'جست‌وجوی رفتارها',
    searchPlaceholder: 'جست‌وجو در زبان روزمره یا برچسب معیار',
    results: 'رفتار نمایش داده شده',
    noResults: 'رفتاری با این جست‌وجو مطابقت ندارد.',
    explore: 'این رفتار را کاوش کنید',
    orientation: 'چند مسیر احتمالی بافت و تنظیم را بدون انتخاب علائم یا ساخت پروفایل ببینید.',
    back: 'همهٔ رفتارها',
    canonicalBehaviour: 'رفتار معیار',
    pathwayHeading: 'چند مسیر آموزشی احتمالی',
    pathwayIntroduction: 'یک مسیر را برای بررسی انتخاب کنید. ترتیب منبع ثابت است و هیچ مسیر رتبه‌بندی، توصیه یا محتمل‌تر معرفی نمی‌شود.',
    possiblePathway: 'مسیر احتمالی',
    selectedPathway: 'مسیر آموزشی انتخاب‌شده',
    context: 'بافت احتمالی',
    contextExplanation: 'بافت می‌تواند تقاضا، ثبات، بروز یا پیامدها را تغییر دهد. بافت اثبات‌کنندهٔ ADHD نیست.',
    regulation: 'مسیر احتمالی تنظیم',
    regulationExplanation: 'این مفهوم تنظیم در این مسیر می‌تواند با رفتار ارتباط داشته باشد. این توضیح، تشخیص سازوکار فردی نیست.',
    pattern: 'الگوی تکرارشوندهٔ احتمالی',
    patternIntro: 'وقتی این وضعیت بارها رخ دهد، ممکن است به یکی از این الگوهای تکرارشونده کمک کند.',
    noPattern: 'در انتشار فعلی دانش، الگوی تکرارشوندهٔ اختیاری برای این رفتار ثبت نشده است.',
    function: 'حوزه‌های احتمالی اثر',
    functionIntro: 'این مثال‌ها حوزه‌های عملکردی احتمالی را توصیف می‌کنند و درجه‌بندی شدت یا ارزیابی فردی اختلال عملکرد نیستند.',
    noFunction: 'در انتشار فعلی دانش، مثال حوزهٔ عملکردی اختیاری برای این رفتار ثبت نشده است.',
    alternatives: 'عوامل احتمالی دیگر',
    alternativesIntro: 'این احتمال‌ها رتبه‌بندی نشده‌اند. کاوشگر تعیین نمی‌کند کدام مورد دربارهٔ یک فرد صدق می‌کند.',
    evidence: 'مشاهدهٔ شواهد این رابطه',
    closeEvidence: 'بستن پیش‌نمایش شواهد',
    evidencePreview: 'پیش‌نمایش بافت‌مند شواهد',
    evidenceLevel: 'سطح شواهد',
    evidenceLimitations: 'محدودیت‌ها',
    relationshipLimitation: 'محدودیت رابطه',
    sourceCount: 'رکورد منبع',
    sourceLanguage: 'فرادادهٔ علمی با زبان معتبر منبع نمایش داده می‌شود.',
    evidenceUnavailable: 'برای این مثال توضیحی، شواهد اختصاصیِ یک رابطه در دسترس نیست.',
    reset: 'بازنشانی این کاوش',
    mapLink: 'این رفتار را در کل سیستم ببینید',
    contextLink: 'بررسی کنید چرا این رفتار ممکن است در موقعیت‌های مختلف تغییر کند',
    invalidTitle: 'رفتار پیدا نشد',
    invalidMessage: 'این شناسهٔ دقیق رفتار معیار در کتابخانهٔ منتشرشده وجود ندارد.',
    invalidPathway: 'این مسیر دقیق به این رفتار تعلق ندارد. حالت پیش‌فرض کاوش نمایش داده شده است.',
    returnLibrary: 'بازگشت به کتابخانهٔ رفتارها',
    semantics: { MODULATES: 'تعدیل می‌کند', CONTRIBUTES_TO: 'کمک می‌کند به', FEEDBACK_WITH: 'بازخورد دارد با' },
  },
} satisfies Readonly<Record<Locale, Record<string, unknown>>>)

export type BehaviourCopy = (typeof behaviourCopy)[Locale]
