import type { Locale } from '../../domain'

export const contextCopy = Object.freeze({
  en: {
    metaLibrary: 'Context & Feedback Explorer | ADHD Interactive Explorer',
    metaDetail: 'Context & Feedback Explorer',
    kicker: 'Context & Feedback Explorer',
    libraryTitle: 'Why can functioning change across situations?',
    librarySummary: 'Explore situational and environmental factors that may modify regulation and behaviour. These are educational relationships, not personal measurements.',
    libraryOrientation: 'Choose one Context factor to inspect its published relationships. Nothing is selected, scored, or saved.',
    mappings: 'published mappings',
    feedbackAvailable: 'Feedback relationship available',
    explore: 'Explore this Context',
    back: 'All Contexts',
    canonicalContext: 'Canonical Context',
    mapLink: 'See this Context in the full system',
    reset: 'Reset this exploration',
    stateHeading: 'Compare qualitative conditions',
    stateIntroduction: 'These are explanatory lenses, not measurements of you or your current situation.',
    supportive: 'More supportive',
    neutral: 'Neutral reference',
    demanding: 'More demanding',
    supportiveDescription: 'Consider how more support or fewer demands could change how this Context interacts with regulation. The published mappings remain possibilities.',
    neutralDescription: 'Read the published relationships without assuming a supportive or demanding direction.',
    demandingDescription: 'Consider how more demands or fewer supports could change regulatory load. This is not a measured personal condition.',
    invalidState: 'That state is not an approved qualitative identifier. The neutral reference is shown.',
    relationshipHeading: 'Possible Regulation and Behaviour relationships',
    relationshipIntroduction: 'Each pathway comes from an explicit production Context mapping. It does not predict that a person will show the related Behaviour.',
    possibleRelationship: 'Possible relationship',
    context: 'Context',
    regulation: 'Related Regulation',
    behaviour: 'Possible Behaviour',
    qualitativeRole: 'Published qualitative role',
    roles: {
      buffering: 'buffering',
      variable: 'variable',
      'increases-demand': 'increases demand',
      interfering: 'interfering',
    },
    modulates: 'may modulate',
    contributes: 'may contribute to',
    regulationMapLink: 'Open related Regulation concept',
    behaviourLink: 'Explore related Behaviour',
    downstreamHeading: 'Downstream possibilities',
    pattern: 'Possible recurring Pattern',
    function: 'Possible Functional Domain',
    noDownstream: 'No optional downstream concept is associated with these Behaviours in the current knowledge release.',
    feedbackHeading: 'Possible Feedback',
    feedbackPrompt: 'What can reinforce this pattern over time?',
    feedbackIntroduction: 'Feedback remains a secondary educational view. A loop is shown only when the current release contains an authoritative FeedbackLoop record.',
    noFeedback: 'No canonical Feedback loop is associated with this Context in the current knowledge release.',
    startingConcept: 'Starting concept',
    downstreamEffect: 'Canonical sequence',
    returningInfluence: 'Returning influence',
    loopMeaning: 'Canonical loop meaning',
    evidence: 'View relationship evidence',
    feedbackEvidence: 'View Feedback evidence',
    closeEvidence: 'Close evidence preview',
    evidencePreview: 'Contextual evidence preview',
    evidenceLimitations: 'Limitations',
    relationshipLimitation: 'Relationship limitation',
    sourceCount: 'source records',
    sourceLanguage: 'Scientific metadata is shown in its authoritative source language.',
    evidenceUnavailable: 'Relationship-specific evidence is unavailable.',
    invalidTitle: 'Context not found',
    invalidMessage: 'This exact canonical Context ID is not part of the published Context library.',
    returnLibrary: 'Return to the Context library',
  },
  fa: {
    metaLibrary: 'کاوشگر بافت و بازخورد | کاوشگر تعاملی ADHD',
    metaDetail: 'کاوشگر بافت و بازخورد',
    kicker: 'کاوشگر بافت و بازخورد',
    libraryTitle: 'چرا عملکرد می‌تواند در موقعیت‌های مختلف تغییر کند؟',
    librarySummary: 'عوامل موقعیتی و محیطی را کاوش کنید که ممکن است تنظیم و رفتار را تعدیل کنند. این روابط آموزشی‌اند، نه اندازه‌گیری شخصی.',
    libraryOrientation: 'یک عامل بافتی را برای دیدن روابط منتشرشدهٔ آن انتخاب کنید. چیزی انتخاب، امتیازدهی یا ذخیره نمی‌شود.',
    mappings: 'نگاشت منتشرشده',
    feedbackAvailable: 'رابطهٔ بازخوردی موجود است',
    explore: 'این بافت را کاوش کنید',
    back: 'همهٔ بافت‌ها',
    canonicalContext: 'بافت معیار',
    mapLink: 'این بافت را در کل سیستم ببینید',
    reset: 'بازنشانی این کاوش',
    stateHeading: 'مقایسهٔ کیفی شرایط',
    stateIntroduction: 'این‌ها زاویه‌های توضیحی‌اند، نه اندازه‌گیری شما یا موقعیت فعلی شما.',
    supportive: 'حمایت‌کننده‌تر',
    neutral: 'مرجع خنثی',
    demanding: 'پرتقاضاتر',
    supportiveDescription: 'بررسی کنید حمایت بیشتر یا تقاضای کمتر چگونه می‌تواند تعامل این بافت با تنظیم را تغییر دهد. نگاشت‌های منتشرشده همچنان احتمال‌اند.',
    neutralDescription: 'روابط منتشرشده را بدون فرض جهت حمایت‌کننده یا پرتقاضا بخوانید.',
    demandingDescription: 'بررسی کنید تقاضای بیشتر یا حمایت کمتر چگونه می‌تواند بار تنظیمی را تغییر دهد. این وضعیت شخصی اندازه‌گیری‌شده نیست.',
    invalidState: 'این مقدار شناسهٔ کیفی تأییدشده نیست. مرجع خنثی نمایش داده می‌شود.',
    relationshipHeading: 'روابط احتمالی تنظیم و رفتار',
    relationshipIntroduction: 'هر مسیر از یک نگاشت صریح بافت در دادهٔ تولید می‌آید و پیش‌بینی نمی‌کند که فرد رفتار مرتبط را نشان خواهد داد.',
    possibleRelationship: 'رابطهٔ احتمالی',
    context: 'بافت',
    regulation: 'تنظیم مرتبط',
    behaviour: 'رفتار احتمالی',
    qualitativeRole: 'نقش کیفی منتشرشده',
    roles: {
      buffering: 'کاهندهٔ فشار',
      variable: 'متغیر',
      'increases-demand': 'افزایندهٔ تقاضا',
      interfering: 'مداخله‌گر',
    },
    modulates: 'ممکن است تعدیل کند',
    contributes: 'ممکن است کمک کند به',
    regulationMapLink: 'مفهوم تنظیم مرتبط را باز کنید',
    behaviourLink: 'رفتار مرتبط را کاوش کنید',
    downstreamHeading: 'پیامدهای احتمالی پایین‌دست',
    pattern: 'الگوی تکرارشوندهٔ احتمالی',
    function: 'حوزهٔ عملکردی احتمالی',
    noDownstream: 'در انتشار فعلی دانش، مفهوم پایین‌دست اختیاری برای این رفتارها ثبت نشده است.',
    feedbackHeading: 'بازخورد احتمالی',
    feedbackPrompt: 'چه چیزی می‌تواند این الگو را در طول زمان تقویت کند؟',
    feedbackIntroduction: 'بازخورد یک نمای آموزشی ثانویه است. حلقه فقط زمانی نمایش داده می‌شود که انتشار فعلی رکورد معتبر FeedbackLoop داشته باشد.',
    noFeedback: 'در انتشار فعلی دانش، حلقهٔ بازخورد معیار برای این بافت ثبت نشده است.',
    startingConcept: 'مفهوم آغازین',
    downstreamEffect: 'توالی معیار',
    returningInfluence: 'اثر بازگشتی',
    loopMeaning: 'معنای معیار حلقه',
    evidence: 'شواهد این رابطه را ببینید',
    feedbackEvidence: 'شواهد بازخورد را ببینید',
    closeEvidence: 'بستن پیش‌نمایش شواهد',
    evidencePreview: 'پیش‌نمایش بافت‌مند شواهد',
    evidenceLimitations: 'محدودیت‌ها',
    relationshipLimitation: 'محدودیت رابطه',
    sourceCount: 'رکورد منبع',
    sourceLanguage: 'فرادادهٔ علمی با زبان معتبر منبع نمایش داده می‌شود.',
    evidenceUnavailable: 'شواهد اختصاصی این رابطه در دسترس نیست.',
    invalidTitle: 'بافت پیدا نشد',
    invalidMessage: 'این شناسهٔ دقیق بافت معیار در کتابخانهٔ منتشرشده وجود ندارد.',
    returnLibrary: 'بازگشت به کتابخانهٔ بافت‌ها',
  },
} as const satisfies Readonly<Record<Locale, Record<string, unknown>>>)

export type ContextCopy = (typeof contextCopy)[Locale]
