import type { Locale } from '../../domain'

export const presentationCopy = Object.freeze({
  en: {
    metaIndex: 'ADHD Presentation Education | ADHD Interactive Explorer',
    metaDetail: 'ADHD Presentation Education',
    kicker: 'Formal clinical terminology',
    indexTitle: 'What are ADHD presentations?',
    indexSummary: 'Presentations are the current clinical terms used to describe which formal ADHD symptom domain or domains are represented. This is education about terminology, not an assessment.',
    orientation: 'Learn about any of the three peer presentations. None is ranked, recommended, or selected for you.',
    formalStatus: 'Current formal presentation',
    learnAbout: 'Learn about this presentation',
    clinicalDomain: 'Associated formal clinical domain',
    clinicalDomains: 'Associated formal clinical domains',
    detailSummary: 'Read the authoritative description, its Clinical Anchor relationship, and the explicit sources attached to this formal term.',
    allPresentations: 'All presentations',
    canonicalId: 'Canonical presentation ID',
    anchorHeading: 'Clinical Anchor relationship',
    anchorIntroduction: 'Clinical Anchors name the formal symptom domains used in presentation terminology. They are educational references here, not a checklist.',
    anchorDefinition: 'Canonical definition',
    distinctionHeading: 'Why this is separate from the explanatory model',
    modelSequence: 'Context → Regulation → Behaviour → Pattern → Functional Domain → Feedback',
    distinctionBody: 'This is an explanatory learning model. Behaviour exploration, Context exploration, and System Map selections do not determine a presentation.',
    modelLink: 'Open the System Map as a separate explanatory model',
    historyHeading: 'Historical terminology, kept separate',
    historicalStatus: 'Historical only',
    historyBoundary: 'This is not a fourth current presentation and is not a separate current disorder or a current canonical synonym for ADHD.',
    safetyHeading: 'Educational boundary',
    safetyTerms: 'This content explains diagnostic terminology.',
    safetyApplication: 'The application does not determine which presentation applies to a person.',
    safetyBehaviour: 'Behaviour exploration elsewhere does not determine a presentation.',
    sourcesHeading: 'Evidence and source preview',
    sourcesIntroduction: 'These are the explicit source records attached to this presentation in the current knowledge release. Follow a source into Evidence / Sources to inspect supporting records without inferring a presentation.',
    sourceLanguage: 'Scientific source metadata remains in its authoritative source language.',
    sourceType: 'Source type',
    relevance: 'Support context',
    citation: 'Citation',
    openSource: 'Open source',
    inspectEvidence: 'Find evidence records using this source',
    showSources: 'View source preview',
    hideSources: 'Close source preview',
    switchHeading: 'Learn about another presentation',
    currentPage: 'Current page',
    invalidTitle: 'Presentation not found',
    invalidMessage: 'This exact ID is not a current formal presentation route.',
    returnIndex: 'Return to Presentation Education',
  },
  fa: {
    metaIndex: 'آموزش presentationهای ADHD | کاوشگر تعاملی ADHD',
    metaDetail: 'آموزش presentationهای ADHD',
    kicker: 'اصطلاحات رسمی بالینی',
    indexTitle: 'presentationهای ADHD چیستند؟',
    indexSummary: 'presentationها اصطلاحات بالینی فعلی برای توصیف این هستند که کدام حوزه یا حوزه‌های رسمی علائم ADHD مطرح‌اند. این بخش آموزش اصطلاحات است، نه ارزیابی.',
    orientation: 'دربارهٔ هر یک از سه presentation هم‌سطح بیاموزید. هیچ‌کدام برای شما رتبه‌بندی، پیشنهاد یا انتخاب نمی‌شود.',
    formalStatus: 'presentation رسمی فعلی',
    learnAbout: 'دربارهٔ این presentation بیاموزید',
    clinicalDomain: 'حوزهٔ رسمی بالینی مرتبط',
    clinicalDomains: 'حوزه‌های رسمی بالینی مرتبط',
    detailSummary: 'توضیح معتبر، رابطهٔ آن با Clinical Anchor و منابع صریح پیوست‌شده به این اصطلاح رسمی را بخوانید.',
    allPresentations: 'همهٔ presentationها',
    canonicalId: 'شناسهٔ canonical presentation',
    anchorHeading: 'رابطه با Clinical Anchor',
    anchorIntroduction: 'Clinical Anchorها حوزه‌های رسمی علائم را در اصطلاحات presentation نام‌گذاری می‌کنند. اینجا مرجع آموزشی‌اند، نه چک‌لیست.',
    anchorDefinition: 'تعریف canonical',
    distinctionHeading: 'چرا این بخش از مدل توضیحی جداست؟',
    modelSequence: 'Context → Regulation → Behaviour → Pattern → Functional Domain → Feedback',
    distinctionBody: 'این یک مدل توضیحی برای یادگیری است. کاوش Behaviour، کاوش Context و انتخاب‌های System Map هیچ presentationی را تعیین نمی‌کنند.',
    modelLink: 'System Map را به‌عنوان یک مدل توضیحی جداگانه باز کنید',
    historyHeading: 'اصطلاح تاریخی، به‌صورت جداگانه',
    historicalStatus: 'فقط تاریخی',
    historyBoundary: 'این مورد presentation چهارم فعلی، اختلال فعلی جداگانه یا مترادف canonical فعلی برای ADHD نیست.',
    safetyHeading: 'مرز آموزشی',
    safetyTerms: 'این محتوا اصطلاحات تشخیصی را توضیح می‌دهد.',
    safetyApplication: 'برنامه تعیین نمی‌کند کدام presentation دربارهٔ یک فرد صدق می‌کند.',
    safetyBehaviour: 'کاوش Behaviour در بخش‌های دیگر presentation را تعیین نمی‌کند.',
    sourcesHeading: 'پیش‌نمایش شواهد و منابع',
    sourcesIntroduction: 'این‌ها رکوردهای منبع صریحی هستند که در انتشار فعلی دانش به این presentation پیوست شده‌اند. برای بررسی رکوردهای پشتیبان، بدون استنباط presentation، منبع را در بخش شواهد و منابع دنبال کنید.',
    sourceLanguage: 'فرادادهٔ علمی منابع به زبان معتبر اصلی خود نمایش داده می‌شود.',
    sourceType: 'نوع منبع',
    relevance: 'زمینهٔ پشتیبانی',
    citation: 'ارجاع',
    openSource: 'باز کردن منبع',
    inspectEvidence: 'یافتن رکوردهای شواهدی که از این منبع استفاده می‌کنند',
    showSources: 'دیدن پیش‌نمایش منابع',
    hideSources: 'بستن پیش‌نمایش منابع',
    switchHeading: 'دربارهٔ presentation دیگری بیاموزید',
    currentPage: 'صفحهٔ فعلی',
    invalidTitle: 'presentation پیدا نشد',
    invalidMessage: 'این شناسهٔ دقیق، مسیر یک presentation رسمی فعلی نیست.',
    returnIndex: 'بازگشت به آموزش presentationها',
  },
} as const satisfies Record<Locale, Record<string, string>>)

export type PresentationCopy = typeof presentationCopy[Locale]
